name: Generate SBOM

permissions:
  contents: read

on:
  workflow_dispatch

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: advanced-security/generate-sbom-action@v1
      id: gensbom
    - uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: ${{ steps.gensbom.outputs.fileName }}
